---
######################################
### vars

- name: Talk to all hosts just so we can learn about them
  hosts: all

  vars_prompt:
    - name: user_username
      prompt: Select username
      private: false

    - name: user_password
      prompt: Select password
      private: true
      confirm: true
      unsafe: true

  tasks:
    - name: Set facts
      ansible.builtin.set_fact:
        user_username: "{{ user_username }}"
        user_password: "{{ user_password }}"

######################################
### roles

- name: Load variables
  hosts: all
  tasks:
    - name: "Packages: Check if variables file exists"
      ansible.builtin.stat:
        path: "vars/{{ group_names[0] }}/{{ ansible_os_family }}.yml"
      register: vars_file
    - name: "Packages: Load variables file"
      ansible.builtin.include_vars: "vars/{{ group_names[0] }}/{{ ansible_os_family }}.yml"
      when: vars_file.stat.exists

- name: Configure hosts - common
  hosts: all
  roles:
    - role: giftpilz0.general.update
    - role: giftpilz0.general.firewalld
    - role: giftpilz0.general.packages
    - role: giftpilz0.general.timezone
    - role: giftpilz0.general.user
    - role: giftpilz0.general.git
    - role: giftpilz0.general.sysutil

- name: Configure hosts - RedHat
  hosts: all
  tasks:
    - name: "include redhat"
      include_role:
        name: giftpilz0.general.dnf
      when:
        - ansible_os_family == "RedHat"

# - name: Configure hosts - workstation
#   hosts: workstation
#   roles:
