---
######################################
### giftpilz0.desktop.pdfgen

pdfgen_document_path: /home/{{ user_username | default(ansible_user) }}/Dokumente/
pdfgen_user: "{{ user_username | default(ansible_user) }}"

######################################
### giftpilz0.general.firewalld

firewalld_zones_define:
  - zone: work
    source: 192.168.10.0/24

firewalld_rules_services:
  - service: ssh
    zone: work
    state: disabled

######################################
### giftpilz0.general.packages

packages_additional_package:
  - SwayNotificationCenter
  - bat
  - brightnessctl
  - eza
  - file-roller
  - gitui
  - htop
  - hypridle
  - hyprland
  - hyprlock
  - hyprpaper
  - keepassxc
  - kitty
  - nmap
  - playerctl
  - snapper
  - sqlite
  - wofi

packages_python_package:
  - pre-commit

packages_rpmfusion_package_state: present

packages_flatpak_repo_state: present
packages_flatpak_package:
  - dev.zed.Zed
